// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VTOP__SYMS_H_
#define VERILATED_VTOP__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "Vtop.h"

// INCLUDE MODULE CLASSES
#include "Vtop___024root.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES) Vtop__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    Vtop* const __Vm_modelp;
    bool __Vm_activity = false;  ///< Used by trace routines to determine change occurred
    uint32_t __Vm_baseCode = 0;  ///< Used by trace routines when tracing multiple models
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    Vtop___024root                 TOP;

    // SCOPE NAMES
    VerilatedScope __Vscope_TOP;
    VerilatedScope __Vscope_tpu;
    VerilatedScope __Vscope_tpu__metadata_regs_i;
    VerilatedScope __Vscope_tpu__metadata_regs_i__scratchpad_metadata;
    VerilatedScope __Vscope_tpu__metadata_regs_i__scratchpad_metadata__unnamedblk1;
    VerilatedScope __Vscope_tpu__sp_i;
    VerilatedScope __Vscope_tpu__sp_i__unnamedblk1;
    VerilatedScope __Vscope_tpu__sp_i__unnamedblk1__unnamedblk2;
    VerilatedScope __Vscope_tpu__state_machine_comb;
    VerilatedScope __Vscope_tpu__state_machine_comb__unnamedblk1;
    VerilatedScope __Vscope_tpu__state_machine_comb__unnamedblk2;
    VerilatedScope __Vscope_tpu__state_machine_comb__unnamedblk3;
    VerilatedScope __Vscope_tpu__state_machine_comb__unnamedblk4;
    VerilatedScope __Vscope_tpu__state_machine_comb__unnamedblk5;
    VerilatedScope __Vscope_tpu__sys_arr;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__0__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__0__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__1__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__1__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__2__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__2__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__3__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__3__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__4__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__4__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__5__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__5__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__6__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__6__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__7__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__0__KET____cols_body__BRA__7__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__0__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__0__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__1__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__1__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__2__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__2__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__3__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__3__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__4__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__4__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__5__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__5__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__6__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__6__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__7__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__1__KET____cols_body__BRA__7__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__0__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__0__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__1__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__1__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__2__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__2__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__3__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__3__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__4__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__4__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__5__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__5__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__6__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__6__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__7__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__2__KET____cols_body__BRA__7__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__0__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__0__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__1__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__1__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__2__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__2__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__3__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__3__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__4__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__4__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__5__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__5__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__6__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__6__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__7__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__3__KET____cols_body__BRA__7__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__0__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__0__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__1__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__1__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__2__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__2__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__3__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__3__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__4__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__4__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__5__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__5__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__6__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__6__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__7__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__4__KET____cols_body__BRA__7__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__0__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__0__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__1__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__1__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__2__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__2__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__3__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__3__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__4__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__4__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__5__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__5__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__6__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__6__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__7__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__5__KET____cols_body__BRA__7__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__0__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__0__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__1__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__1__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__2__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__2__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__3__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__3__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__4__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__4__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__5__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__5__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__6__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__6__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__7__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__6__KET____cols_body__BRA__7__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__0__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__0__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__1__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__1__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__2__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__2__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__3__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__3__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__4__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__4__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__5__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__5__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__6__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__6__KET____mac_grid;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__7__KET__;
    VerilatedScope __Vscope_tpu__sys_arr__rows_body__BRA__7__KET____cols_body__BRA__7__KET____mac_grid;

    // SCOPE HIERARCHY
    VerilatedHierarchy __Vhier;

    // CONSTRUCTORS
    Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp);
    ~Vtop__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
};

#endif  // guard
